export const APP_ERRORS = {
  EMAIL_IN_USE: "EMAIL_IN_USE",
  EMAIL_NOT_REGISTERED: "EMAIL_NOT_REGISTERED",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  TOKEN_MISSING: "TOKEN_MISSING",
  TOKEN_INVALID: "TOKEN_INVALID",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  USER_NOT_FOUND: "USER_NOT_FOUND",
} as const;

export type AppErrorCode = (typeof APP_ERRORS)[keyof typeof APP_ERRORS];
